// svelte/src/components/Routing.svelte
<script>
	import { Router, Route } from "svelte-routing";
	import AllDrivers from "../views/AllDrivers.svelte";
	import Driver from "../views/Driver.svelte";
</script>

<style>
</style>

<Router>
	<div>
		<Route path="/" component={AllDrivers} />
		<Route path="/drivers/:id">
			<Driver />
		</Route>
	</div>
</Router>

// react-app/src/components/Routing.tsx
import React from 'react';
import {BrowserRouter as Router, Switch, Route} from 'react-router-dom';
import Driver from '../views/Driver';
import AllDrivers from '../views/AllDrivers';

const Routing = () => {
  return (
    <Router>
      <Switch>
        <Route exact path="/">
          <AllDrivers />
        </Route>
        <Route path="/drivers/:id">
          <Driver />
        </Route>
      </Switch>
    </Router>
  );
};

export default Routing;
