// svelte/src/views/AllDrivers.svelte
<script>
	import { Link } from "svelte-routing";
	import GridHeader from "../components/grid/GridHeader.svelte";
	import ChampRow from "../components/grid/ChampRow.svelte";
	import { getAge } from "../utils";
	import { API } from "../constants";

	const fetchDrivers = (async () => {
		const response = await fetch(API);
		return await response.json();
	})();
</script>

<style type="text/scss">
	.row {
		display: grid;
		grid-template-columns: 3fr 1fr 2fr 3fr 2fr 2fr 2fr;
		min-height: 50px;
		align-items: center;
		border-top: 1px solid #555;

		& > div {
			min-height: 50px;
			display: flex;
			align-items: center;
		}
	}
</style>

<GridHeader />
{#await fetchDrivers}
	<p>...waiting</p>
{:then data}
	{#each data as driver}
		<Link to={`/drivers/${driver.id}`}>
			<div class="row">
				<div>{driver.name}</div>
				<div>{getAge(driver.born, driver.died)}</div>
				<div>{driver.country}</div>
				<div>{driver.teams}</div>
				<div>{driver.poles}</div>
				<div>{driver.wins}</div>
				<ChampRow champs={driver.championships} />
			</div>
		</Link>
	{/each}
{:catch err}
	<p>Oh dang! {err}</p>
{/await}

// react-app/src/views/AllDrivers.tsx
import React from 'react';
import {useQuery} from 'react-query';
import styled from 'styled-components';
import Row from '../components/grid/Row';
import {API} from '../constants';
import {RowProps} from '../components/grid/Row';
import HeaderRow from '../components/grid/HeaderRow';

export const RowContainer = styled.div`
  .row {
    display: grid;
    grid-template-columns: 3fr 1fr 2fr 3fr 2fr 2fr 2fr;
    min-height: 50px;
    align-items: center;
    border-top: 1px solid #555;
  }
`;

const AllDrivers = () => {
  const {isLoading, error, data} = useQuery('repoData', () =>
    fetch(API).then((res) => res.json())
  );

  if (isLoading) return <p>...loading</p>;
  if (error) return <p>An error has occurred: {error.message}</p>;

  console.log(data);

  return (
    <div>
      <HeaderRow />
      {data.map(
        ({
          id,
          name,
          born,
          died,
          country,
          teams,
          poles,
          wins,
          championships,
        }: RowProps) => (
          <RowContainer>
            <Row
              styleType="row"
              key={id}
              name={name}
              born={born}
              died={died}
              country={country}
              teams={teams}
              poles={poles}
              wins={wins}
              championships={championships}
            />
          </RowContainer>
        )
      )}
    </div>
  );
};

export default AllDrivers;
