// svelte/src/components/grid/GridHeader.svelte
<script>
</script>

<style type="text/scss">
	.grid-container {
		position: sticky;
		top: 0;
		display: grid;
		background: #fff;
		z-index: 2;
		border-bottom: 1px solid #555;
	}
</style>

<div class="grid-container">
	<div class="header row">
		<div>Name</div>
		<div>Age</div>
		<div>Country</div>
		<div>Team(s)</div>
		<div>Poles</div>
		<div>Wins</div>
		<div>Championship(s)</div>
	</div>
</div>

// src/components/grid/GridHeader.vue
<template>
  <div class="grid-container">
    <div class="header row">
      <div>Name</div>
      <div>Age</div>
      <div>Country</div>
      <div>Team(s)</div>
      <div>Poles</div>
      <div>Wins</div>
      <div>Championship(s)</div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'GridHeader',
};
</script>

<style lang="scss" scoped>
.header {
  background: #fff;
}
</style>
