// svelte/src/components/Row.svelte
<script>
	export let driver;
	import { Link } from "svelte-routing";
	import ChampRow from "../components/grid/ChampRow.svelte";
	import TeamsRow from "../components/grid/TeamsRow.svelte";
	import AgeRow from "./grid/AgeRow.svelte";
</script>

<style>
</style>

<Link to={`/drivers/${driver.id}`}>
	<div class="row">
		<div>{driver.name}</div>
		<AgeRow born={driver.born} died={driver.died} />
		<div>{driver.country}</div>
		<TeamsRow teams={driver.teams} />
		<div>{driver.poles}</div>
		<div>{driver.wins}</div>
		<ChampRow champs={driver.championships} />
	</div>
</Link>

// react/src/components/grid/Row.tsx
import React, {FC} from 'react';
import {getAge} from '../../utils';

export interface RowProps {
  id?: string;
  name?: string;
  born?: string;
  died?: string;
  country?: string;
  teams?: string;
  poles?: string;
  wins?: string;
  championships?: string;
}

const Row: FC<RowProps> = ({
  id,
  name,
  born,
  died,
  country,
  teams,
  poles,
  wins,
  championships,
}) => {
  const age = getAge(born, died);

  return (
    <>
      <div>{name}</div>
      <div>{age}</div>
    </>
  );
};

export default Row;
