// svelte/src/components/grid/Row.svelte
<script>
	export let driver;
	import { Link } from "svelte-routing";
	import ChampRow from "./ChampRow.svelte";
	import TeamsRow from "./TeamsRow.svelte";
	import AgeRow from "./AgeRow.svelte";
</script>

<style>
</style>

<Link to={`/drivers/${driver.id}`}>
	<div class="row">
		<div>{driver.name}</div>
		<AgeRow born={driver.born} died={driver.died} />
		<div>{driver.country}</div>
		<TeamsRow teams={driver.teams} />
		<div>{driver.poles}</div>
		<div>{driver.wins}</div>
		<ChampRow champs={driver.championships} />
	</div>
</Link>

// react-app/src/components/grid/Row.tsx
import React, {FC} from 'react';
import {getAge} from '../../utils';

export interface RowProps {
  name?: string;
  born?: string;
  died?: string;
  country?: string;
  teams?: string;
  poles?: string;
  wins?: string;
  championships?: string;
  styleType?: string;
}

const Row: FC<RowProps> = ({
  name,
  born,
  died,
  country,
  teams,
  poles,
  wins,
  championships,
  styleType,
}) => {
  const age = getAge(born, died);

  return (
    <div className={styleType}>
      <div>{name}</div>
      <div style={{color: died ? 'red' : ''}}>{age}</div>
      <div>{country}</div>
      <div>{teams}</div>
      <div>{poles}</div>
      <div>{wins}</div>
      <div>{championships}</div>
    </div>
  );
};

export default Row;
