// svelte/src/components/grid/TeamsRow.svelte
<script>
	import { onMount } from "svelte";
	export let teams;
	let output;

	function cycleTeams() {
		let current = 0;

		setInterval(() => {
			if (teams[current] === undefined) {
				current = 0;
				output = teams[0];
			} else {
				output = teams[current];
			}
			current++;
		}, 2000);
	}

	onMount(() => {
		output = teams[0];
		if (teams.length === 1) {
			output = teams[0];
		} else {
			cycleTeams();
		}
	});
</script>

<style>
	/* your styles go here */
</style>

<div>{output}</div>

// vue/src/components/grid/TeamsRow.vue
<template>
  <div>
    <p>{{ output }}</p>
  </div>
</template>

<script>
export default {
  name: 'TeamRow',
  props: ['teams'],
  data: () => ({
    output: '',
  }),
  computed: {
    showTeams() {
      if (this.teams.length === 1) {
        return this.teams[0];
      } else {
        return this.cycleTeams();
      }
    },
  },
  methods: {
    cycleTeams() {
      let current = 0;
      this.output = this.teams[0];

      setInterval(() => {
        if (this.teams[current] === undefined) {
          current = 0;
          this.output = this.teams[0];
        } else {
          this.output = this.teams[current];
        }
        current++;
      }, 2000);
    },
  },
  created() {
    this.cycleTeams();
  },
};
</script>

<style></style>
